-- Retrofit Business & Finance sector: AI and robotics horizon ratings for 20 roles
-- ai_rating_2030_2035, ai_rating_2040_2045, robotics_rating_2030_2035, robotics_rating_2040_2045, robotics_description

UPDATE career_roles SET
  ai_rating_2030_2035 = v.ai1,
  ai_rating_2040_2045 = v.ai2,
  robotics_rating_2030_2035 = v.r1,
  robotics_rating_2040_2045 = v.r2,
  robotics_description = v.rdesc
FROM (VALUES
  ('Accountant (Qualified)',             5, 8, 1, 1, 'Accounting work is entirely desk-based and data-driven, with no physical processes amenable to robotic substitution across either horizon. Scotland''s major accountancy practices -- including KPMG Edinburgh, PwC Glasgow, and Johnston Carmichael -- operate in entirely cognitive and relational environments. A flat rating of 1 across both horizons reflects the digital-only nature of the role.'),
  ('Actuary',                            4, 7, 1, 1, 'Actuarial work involves quantitative modelling, professional judgement, and communication with boards and regulators, with no physical component that robotics could address. Scotland''s actuarial community is concentrated in Edinburgh''s financial district, particularly at abrdn and major insurance firms, all of which operate in entirely cognitive environments. A flat rating of 1 across both horizons reflects the nature of the profession.'),
  ('AI-Savvy Financial Analyst',         3, 6, 1, 1, 'Financial analysis work is inherently digital and office-based, with no physical processes amenable to robotic substitution. The role''s value lies in interpreting AI outputs, constructing investment narratives, and engaging clients -- activities that have no robotics equivalent. A flat rating of 1 across both horizons reflects the knowledge-work nature of the role.'),
  ('Bank Clerk / Cashier',               7, 9, 1, 2, 'Physical banking interactions occur at counters and service desks, and while cash-handling automation has accelerated branch transformation, this represents digital substitution rather than physical robotics deployment. Scotland''s branch network has contracted significantly -- RBS/NatWest, Lloyds Banking Group, and Bank of Scotland have all reduced footprints -- with app-based banking as the primary driver. The drift from 1 to 2 in the second horizon reflects service robots for customer navigation in larger branches, not displacement of any remaining counter functions.'),
  ('Bookkeeper / Payroll Clerk',         7, 9, 1, 1, 'Bookkeeping and payroll work is entirely desk-based data processing with no physical component amenable to robotic substitution. Automation risk in this role is entirely AI-driven -- software processing of invoices, reconciliation, and payroll calculations -- rather than physical. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway.'),
  ('Business Analyst',                   4, 7, 1, 1, 'Business analysis work is relational, cognitive, and workshop-based, with no physical processes that robotics could address. Requirements gathering, stakeholder facilitation, and change management occur in meeting rooms and collaborative settings across Scotland''s financial and public sectors. A flat rating of 1 across both horizons reflects the knowledge-work nature of the role.'),
  ('Data Governance Manager (Finance)',  2, 5, 1, 1, 'Data governance work is policy-setting, oversight, and framework design -- entirely cognitive and organisational in nature, with no physical automation pathway in either horizon. The role exists specifically to provide human accountability over AI-driven financial systems, making it structurally resistant to the automation it governs. A flat rating of 1 across both horizons reflects the strategic and advisory character of the function.'),
  ('Economist',                          4, 7, 1, 1, 'Economic research, modelling, and advisory work is entirely desk-based and cognitive, with no physical processes amenable to robotic substitution. Scotland''s economists work across the Scottish Government Economic and Statistics Service, the Scottish Fiscal Commission, the Fraser of Allander Institute, and major financial institutions -- all operating in purely knowledge-work environments. A flat rating of 1 across both horizons reflects the nature of the profession.'),
  ('Entrepreneur / Small Business Owner',3, 4, 1, 1, 'Business ownership is a fundamentally cognitive, relational, and strategic function with no physical tasks that robotics would substitute at the ownership level. Whether operating in Edinburgh''s tech startup ecosystem, the Highlands food and drink sector, or Glasgow''s creative industries, entrepreneurs are decision-makers and relationship-builders rather than physical process operators. A flat rating of 1 across both horizons reflects the strategic nature of the owner role, irrespective of whether the underlying business uses automation.'),
  ('Financial Adviser',                  3, 6, 1, 1, 'Financial advice is delivered through in-person and remote meetings, requiring trust, emotional intelligence, and nuanced communication -- none of which are physically automatable. FCA-regulated advisers at firms such as Brewin Dolphin Edinburgh, Quilter, and independent Scottish IFA practices operate in entirely relational environments. A flat rating of 1 across both horizons reflects the interpersonal delivery model of the profession.'),
  ('Financial AI Compliance Specialist', 2, 5, 1, 1, 'Compliance and governance work is policy-driven, analytical, and human-accountability-centred, with no physical component amenable to robotic substitution. The role exists specifically to provide human oversight of AI systems in FCA-regulated environments, making it structurally resistant to the automation it governs. A flat rating of 1 across both horizons reflects the oversight and accountability nature of the function.'),
  ('FinTech Product Manager',            3, 6, 1, 1, 'Product management work is entirely cognitive and interpersonal -- strategy, roadmapping, stakeholder alignment, and user research -- with no physical tasks that robotics could address. Scotland''s growing FinTech sector, anchored by FintechScotland and firms in Edinburgh''s financial quarter, operates entirely in knowledge-work environments. A flat rating of 1 across both horizons reflects the nature of the role.'),
  ('Forensic AI Auditor',                2, 5, 1, 1, 'AI audit work is investigative, analytical, and accountability-driven, with no physical component amenable to robotic substitution. The role''s purpose is to scrutinise AI systems, which makes it inherently resistant to AI-driven displacement -- and the same logic applies to robotic substitution. A flat rating of 1 across both horizons reflects the oversight and verification nature of the function.'),
  ('HR Manager / Recruitment Consultant',4, 7, 1, 1, 'HR and recruitment work is inherently interpersonal -- interviewing, mediation, culture development, and employment law application -- with no physical processes that robotics could address. Scotland''s HR community spans NHS Scotland, Scottish Government, and major employers such as Scottish Power and Barclays'' Glasgow operations. A flat rating of 1 across both horizons reflects the relational delivery model of the profession.'),
  ('Insurance Underwriter',              6, 9, 1, 1, 'Insurance underwriting is an office-based cognitive and analytical function with no physical processes amenable to robotic substitution. Automation risk in this role is entirely AI-driven -- algorithmic pricing and risk assessment -- rather than physical. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway in this sector.'),
  ('Investment Banker',                  4, 7, 1, 1, 'Investment banking work is deal-driven, relationship-intensive, and judgment-centred -- conducted in meeting rooms, boardrooms, and client settings -- with no physical processes that robotics could address. Scotland''s investment and asset management presence is concentrated in Edinburgh, including Baillie Gifford, abrdn, and Nucleus Financial. A flat rating of 1 across both horizons reflects the purely cognitive and relational nature of the role.'),
  ('Management Consultant',              4, 8, 1, 1, 'Management consulting work is entirely cognitive, relational, and presentation-based, with no physical processes amenable to robotic substitution. Consultants working across Scotland''s public and private sectors -- from KPMG''s Scottish Government engagements to Deloitte''s energy sector work -- operate in knowledge-work environments without any physical automation pathway. A flat rating of 1 across both horizons reflects the nature of the profession.'),
  ('Marketing Manager / Brand Manager',  4, 7, 1, 1, 'Marketing and brand management work is creative, strategic, and client-facing, with no physical processes that robotics could address. Scotland''s marketing community operates across Edinburgh''s financial services sector, Glasgow''s creative agencies, and national brands such as VisitScotland and Scottish Enterprise. A flat rating of 1 across both horizons reflects the cognitive and creative nature of the role.'),
  ('Mortgage Adviser',                   4, 7, 1, 1, 'Mortgage advice is delivered through client meetings -- in person and remotely -- requiring trust, case complexity navigation, and FCA-regulated professional judgement, with no physical automation pathway in either horizon. CeMAP-qualified advisers at firms including Clydesdale Bank, Scottish Building Society, and independent brokers operate in entirely relational environments. A flat rating of 1 across both horizons reflects the interpersonal and regulatory delivery model of the profession.'),
  ('Tax Adviser',                        5, 8, 1, 1, 'Tax advice is an office-based cognitive function with no physical processes amenable to robotic substitution. CIOT and ATT-qualified advisers at firms including Deloitte Edinburgh, Johnston Carmichael, and Chiene + Tait operate in entirely knowledge-work environments. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway in taxation.')
) AS v(title, ai1, ai2, r1, r2, rdesc)
WHERE career_roles.title = v.title
  AND career_roles.career_sector_id = (SELECT id FROM career_sectors WHERE name ILIKE '%business%' OR name ILIKE '%finance%' LIMIT 1);
