-- Law & Justice sector: horizon rating retrofit
-- Removes Barrister (England & Wales role, no Scottish equivalent in this DB),
-- then populates ai_rating_2030_2035, ai_rating_2040_2045,
-- robotics_rating_2030_2035, robotics_rating_2040_2045, and robotics_description
-- for the remaining 14 roles.

-- Step 1: remove Barrister (FK dependents deleted first in the live session)
DELETE FROM career_roles
WHERE title = 'Barrister'
  AND career_sector_id = (SELECT id FROM career_sectors WHERE name = 'Law & Justice');

-- Step 2: bulk UPDATE horizon ratings
UPDATE career_roles SET
  ai_rating_2030_2035      = v.ai1,
  ai_rating_2040_2045      = v.ai2,
  robotics_rating_2030_2035 = v.r1,
  robotics_rating_2040_2045 = v.r2,
  robotics_description      = v.rdesc
FROM (VALUES
  ('Advocate',                        3, 5, 1, 1, 'Legal advocacy is entirely court-based and relational, with no physical processes amenable to robotic substitution. Members of the Faculty of Advocates appear in the Court of Session, the High Court of Justiciary, and the Sheriff Appeal Court -- environments where oral argument, judicial relationship, and professional judgment are the core deliverable. A flat rating of 1 across both horizons reflects the courtroom and chambers nature of the profession.'),
  ('AI Compliance / Ethics Specialist', 2, 4, 1, 1, 'AI compliance and ethics work is policy-driven, deliberative, and accountability-centred, with no physical processes amenable to robotic substitution. The role exists specifically to provide human oversight of AI systems in regulated environments, making it structurally resistant to the automation it governs. Scotland''s AI governance landscape spans the Scottish AI Register, the Information Commissioner''s Office Scotland office, and public sector AI adoption frameworks. A flat rating of 1 across both horizons reflects the oversight and accountability nature of the function.'),
  ('Court Clerk',                     6, 8, 1, 1, 'Court administration involves scheduling, record management, case file processing, and procedural documentation -- all of which are heavily exposed to AI-driven automation. Scotland''s Sheriff Courts, Justice of the Peace Courts, and the Court of Session all operate administrative functions that are progressively digitising under the Scottish Courts and Tribunals Service''s digital transformation programme. A flat rating of 1 across both horizons reflects the desk-based and digital nature of the automation pathway.'),
  ('LawTech Consultant',              3, 5, 1, 1, 'LawTech consulting combines legal domain knowledge with technology implementation -- a mixed profile where client advisory and change management work persists while the technical build layer automates. Scotland''s legal technology community is growing, anchored by the Law Society of Scotland''s technology working groups and Edinburgh''s concentration of legal services firms. A flat rating of 1 across both horizons reflects the knowledge-work and relational nature of the role.'),
  ('Legal AI Product Manager',        3, 6, 1, 1, 'Legal AI product management is strategic, relational, and roadmap-driven, with no physical automation pathway in either horizon. Near-term, human judgment in legal domain translation and stakeholder alignment is strongly differentiated; by 2045, AI systems generate roadmaps and synthesise user research substantially. Scotland''s legal tech product community is concentrated around Edinburgh''s financial and legal services cluster. A flat rating of 1 across both horizons reflects the knowledge-work nature of the role.'),
  ('Legal Data Analyst',              4, 6, 1, 1, 'Legal data analysis combines data skills with legal domain knowledge -- the domain expertise layer adds resilience relative to a generic data analyst role, but the analytical and reporting functions are progressively automated. Scottish legal data work spans court statistics, regulatory reporting for the Law Society of Scotland, and litigation analytics at larger firms. A flat rating of 1 across both horizons reflects the desk-based digital nature of the role.'),
  ('Legal Secretary',                 6, 8, 1, 1, 'Legal secretarial work centres on document preparation, correspondence, scheduling, and file management -- all of which are among the most AI-automatable office functions. Scotland''s legal firms from Brodies and Shepherd and Wedderburn to high-street solicitor practices are already deploying AI-assisted drafting and document management tools. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway.'),
  ('Legal Technologist',              3, 5, 1, 1, 'Legal technology work is advisory, implementation-focused, and client-facing -- a knowledge-work role with no physical automation pathway. The value lies in translating legal workflow requirements into technology solutions and training practitioners, functions that require contextual and relational judgment. A flat rating of 1 across both horizons reflects the desk-based and consultative nature of the profession.'),
  ('Paralegal',                       6, 8, 1, 1, 'Paralegal work centres on document review, legal research, disclosure processing, and standard document drafting -- precisely the tasks that drove 82% of UK lawyers to adopt AI in 2024. AI-assisted document review, contract analysis, and case research tools are already substantially reducing the volume of paralegal hours required per matter at Scottish firms. Entry-level paralegal roles face the sharpest near-term displacement pressure of any role in the legal sector. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway.'),
  ('Police Officer',                  2, 3, 1, 1, 'Policing is built on physical presence, community relationships, and in-person enforcement -- with no physical processes amenable to robotic substitution. Police Scotland''s 13 divisions operate across environments ranging from rural Highland communities to Glasgow city centre where human presence, de-escalation judgment, and community trust are the core function. Drone surveillance and AI-assisted crime analysis are tools deployed by officers, not replacements for them. A flat rating of 1 across both horizons reflects the physical and relational nature of the role.'),
  ('Prison Officer',                  2, 3, 1, 2, 'Prison custody work is physical, interpersonal, and safety-critical, with no meaningful robotic substitution possible in the near term. Scottish Prison Service facilities from HMP Barlinnie to HMP Grampian require constant human presence for safe custody, de-escalation, and rehabilitation support. The drift from 1 to 2 in the second horizon reflects automated cell monitoring, perimeter surveillance, and controlled access systems becoming standard across Scottish Prison Service estates -- augmenting rather than displacing officer functions.'),
  ('Procurator Fiscal Depute',        3, 5, 1, 1, 'The Procurator Fiscal service is unique to Scotland, operating under the Crown Office and Procurator Fiscal Service to investigate deaths and prosecute crime. Case preparation, disclosure review, and standard documentation are progressively automated; court advocacy, Lord Advocate instruction, and complex prosecutorial judgment remain human. A flat rating of 1 across both horizons reflects the courtroom and investigative nature of the core role.'),
  ('Solicitor (Junior/Trainee)',      6, 7, 1, 1, 'Junior and trainee solicitors in Scotland carry out the document-intensive, research-heavy work that AI tools are most capable of automating -- disclosure review, standard contract drafting, legal research, and due diligence. The Law Society of Scotland''s traineeship system places newly qualified solicitors in exactly the roles most exposed to near-term AI displacement. The Anthropic Economic Index and Stanford research both identify early-career knowledge workers in AI-exposed sectors as the group experiencing the sharpest employment pressure since 2022. A flat rating of 1 across both horizons reflects the digital-only nature of the automation pathway.'),
  ('Solicitor (Senior) / Partner',    3, 5, 1, 1, 'Senior solicitors and partners at Scottish firms -- from Pinsent Masons and CMS to specialist boutiques -- derive their value from client relationships, strategic judgment, complex transaction oversight, and business development, none of which are physically automatable. The junior/senior split in legal AI exposure is one of the most pronounced in any profession: the same AI tools that threaten junior roles actively increase senior productivity. A flat rating of 1 across both horizons reflects the relational and strategic nature of the senior role.')
) AS v(title, ai1, ai2, r1, r2, rdesc)
WHERE career_roles.title = v.title
  AND career_roles.career_sector_id = (SELECT id FROM career_sectors WHERE name = 'Law & Justice');
