-- Retrofit Education & Teaching sector (13 roles) with four horizon rating columns.
-- Primary Teacher (pilot row) is excluded; all other sector roles were NULL before this migration.

UPDATE career_roles SET
  ai_rating_2030_2035 = v.ai1,
  ai_rating_2040_2045 = v.ai2,
  robotics_rating_2030_2035 = v.r1,
  robotics_rating_2040_2045 = v.r2,
  robotics_description = v.rdesc
FROM (VALUES
  ('Additional Support Needs Teacher',    2, 3, 2, 3, 'Assistive robotics such as Leka and MILO robots are used in some Scottish ASN units to support communication and social skills development in autistic pupils, making robotics more present in this role than in mainstream teaching. These tools function as supplementary therapeutic aids under teacher direction, not displacement agents. GTCS registration and the requirement for qualified professional judgement in complex multi-agency casework anchors the role against substitution. The drift from 2 to 3 by mid-career reflects broader adoption of assistive robotics across Highland, Orkney, and central belt ASN provisions, not any reduction in teaching scope.'),
  ('AI Literacy Curriculum Developer',    3, 4, 1, 1, 'This is a desk-based curriculum design role with negligible physical automation risk across both horizons. Robotic systems have no meaningful pathway into the work of designing teaching frameworks, writing learning outcomes, or adapting content for different age groups. A rating of 1 in both periods reflects the cognitive and creative nature of the work rather than any physical process that robotics could supplant.'),
  ('Digital Learning Designer',           4, 5, 1, 1, 'Learning design work is inherently digital and desk-based, with negligible robotics exposure across both horizons. Robotic systems have no meaningful pathway into user research, storyboarding, visual design, or the client engagement that defines instructional design practice. A flat rating of 1 in both windows reflects the knowledge-and-creativity nature of the role.'),
  ('Early Years Teacher',                 2, 3, 1, 1, 'Physical care routines, sensory play, and the minute-by-minute responsiveness that characterises early years practice make this one of the most robotics-resistant roles in the sector. Some Scottish nurseries have introduced Bee-Bot floor robots and similar programmable toys as early digital literacy tools, but these are pupil-facing learning aids rather than teacher substitutes. GTCS EYTS registration and the Care Inspectorate inspection regime anchor the role under a dual regulatory framework, and the rating remains at 1 across both horizons.'),
  ('Educational Psychologist',            2, 3, 1, 1, 'Educational psychology practice centres on direct child and family assessment, therapeutic intervention, and multi-agency collaboration, none of which are physically automatable in any meaningful sense. Some assessment screening tools may use automated scoring, but the professional judgement, report writing, and case formulation work of an HCPC-registered psychologist sits far outside robotics displacement pathways. Scottish local authority teams, including City of Edinburgh and Fife Educational Psychology Services, operate as professional advisory bodies where human accountability is regulatory, not optional. A flat rating of 1 across both horizons reflects the clinical nature of the role.'),
  ('FE Lecturer',                         3, 4, 1, 2, 'FE lecturing in Scotland encompasses a wide range of settings from Inverness College UHI to City of Glasgow College, and robotics exposure varies by subject specialism. Vocational programmes in engineering, construction, and digital technology increasingly use robotics as curriculum content and student-facing learning tools, but the lecturer role itself is not subject to physical automation risk. Teaching qualification requirements and, in some FE contexts, GTCS registration anchor the role under Scottish professional standards. The drift from 1 to 2 in the second horizon reflects classroom robotic assistants and automated practical demonstrations becoming mainstream in vocational settings without threatening the educator function.'),
  ('Learning Technologist',               2, 3, 1, 1, 'Learning technology work is advisory, evaluative, and training-oriented, with no physical processes amenable to robotic substitution. The role''s growth trajectory -- expected to accelerate as Scottish schools and colleges navigate AI tool procurement -- involves platform governance, staff CPD delivery, and digital equity assurance that are inherently human. A flat rating of 1 across both horizons reflects the knowledge-work nature of the role.'),
  ('Nursery Practitioner / Childcare Worker', 1, 2, 1, 1, 'Physical nurturing, sensory play, feeding supervision, and the constant attentiveness that infant and toddler care requires places this role at the far end of robotics-resistance. Some nurseries use Bee-Bot toys and simple interactive robots as educational play aids for older children, but these are child-facing tools rather than practitioner substitutes. Scottish Social Services Council (SSSC) registration requirements and the Care Inspectorate staffing ratio enforcement further anchor the role against any substitution. A flat rating of 1 across both horizons reflects one of the most automation-resistant occupational profiles in the dataset.'),
  ('Online / AI-Assisted Tutoring Coordinator', 3, 4, 1, 1, 'Coordination and oversight work for AI tutoring platforms is desk-based and human-facing, with negligible robotics exposure. The role involves student welfare monitoring, teacher liaison, platform governance, and learning outcome review -- activities requiring professional judgement rather than physical presence. A flat rating of 1 across both horizons reflects the managerial and pastoral nature of the coordination function.'),
  ('School Librarian',                    3, 4, 2, 3, 'Physical book shelving and collection management have been the primary targets of library robotics in large academic and public libraries, though automated shelving systems remain rare in Scottish secondary schools as of the mid-2020s. Some City of Edinburgh and Glasgow City Council school libraries are exploring hybrid physical-digital catalogue management, but capital constraints limit deployment. The drift from 2 to 3 in the second horizon reflects gradual adoption of automated returns and shelving peripherals in larger school libraries rather than any displacement of the student-facing role.'),
  ('Secondary Teacher',                   3, 4, 1, 2, 'Secondary teaching in Scotland mirrors the robotics profile of Primary teaching: GTCS registration and the relational core of the role anchor it against substitution across both horizons. Some subjects -- Computing, Engineering Science, and Physics -- already use educational robotics as curriculum content, and automated classroom peripherals are present in a small number of urban schools. The drift from 1 to 2 in the second window reflects mainstream adoption of robotic classroom assistants in Scotland''s newer builds, not any change in the teacher''s professional function.'),
  ('Teaching Assistant',                  2, 3, 2, 3, 'Teaching assistants working in ASN and additional support contexts already encounter assistive robotics more than most education staff, with tools such as Leka and Bee-Bot used in Scottish special schools and resourced mainstream settings. Physical 1:1 support, behaviour de-escalation, and the continuous supervisory presence required for complex additional needs pupils remain fundamentally human. The drift from 2 to 3 in the second horizon reflects assistive robotics becoming standard toolkit in SEN contexts across Scotland''s 32 local authority areas, requiring TAs to operate and supervise these systems rather than be displaced by them.'),
  ('Youth Worker (CLD)',                  2, 2, 1, 1, 'Youth work and community learning practice is built on outreach, trust, and presence in communities -- from Drumchapel Community Learning to Dundee''s outreach services -- with no physical processes amenable to robotics substitution. CLD workers registered with GTCS under Scotland''s professional standards framework operate in settings such as youth clubs, community centres, and outdoor education venues where robotic systems would be entirely out of place in the foreseeable future. A flat rating of 1 across both horizons reflects the irreducibly relational and community-embedded nature of the role.')
) AS v(title, ai1, ai2, r1, r2, rdesc)
WHERE career_roles.title = v.title
  AND career_roles.career_sector_id = (SELECT id FROM career_sectors WHERE name ILIKE '%education%' OR name ILIKE '%teach%' LIMIT 1);
